GET http://localhost:3000/experiences

###

PUT http://localhost:3000/experiences/update
Content-Type: application/json

{ 
  "_id": "659fedc66cb1f466ce590fb9",
  "isReviewed": true
}

###

DELETE http://localhost:3000/experiences/delete
Content-Type: application/json

{ 
  "_id": "659fedc66cb1f466ce590fb9"
}

